branches:
  only:
    - master

language: c

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      env: USE_HARD_LINKS=false
    - os: linux
      dist: trusty
      sudo: required
      env: DISPLAY=:99.0 CC=clang CXX=clang++ npm_config_clang=1 USE_HARD_LINKS=false
      compiler: clang

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.npm
  - $HOME/.nvm

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - openjpeg-tools # or libopenjp2-tools
      - libx11-dev
      - libxkbfile-dev
      - libsecret-1-dev
      - xvfb

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16;
    fi

install:
- nvm install 8.3
- node --version
- npm --version
- npm install
- npm run build

script:
- node --version
- npm --version
- npm run test:prepare:ci
- npm run test:unit
# - npm run test:integration
# - npm run test:mainview
# - npm run test:extension
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    npm run publish-mac;
  else
    npm run publish-linux;
  fi
