branches:
  only:
    - master

platform:
  - x64

environment:
  global:
    TEST_JUNIT_XML_ROOT: c:\projects\junit-test-results
    NODE_VERSION: 12

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%APPDATA%\npm'

install:
  - git submodule update --init --recursive
  # Install the version if available on Appveyor
  # - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  # Install the version regardless if available on Appveyor
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:NODE_VERSION) $env:PLATFORM
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install
  - npm run build

build_script:
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (
      npm run publish-win
    ) ELSE (
      npm run pack
    )

test_script:
  - npm run test:prepare:ci
  - npm run test:unit
  - npm run test:integration
  - npm run test:mainview
  - npm run test:extension

on_finish:
  # upload results to AppVeyor
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $endpoint = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      Get-ChildItem -Path $env:TEST_JUNIT_XML_ROOT -Recurse -File -Name -Include "*.xml" | ForEach-Object {
        $full = "$($env:TEST_JUNIT_XML_ROOT)\$($_)"
        Write-Output "Uploading JUnit XML file $($full)"
        $wc.UploadFile($endpoint, $full)
      }
