name: CI

on: [push, pull_request]

jobs:
  mac:
    runs-on: macos-latest

    env:
      USE_HARD_LINKS: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install
      run: npm install

    - name: Build
      run: npm run build

    - name: Prepare
      run: npm run test:prepare:ci

    - name: Unit Test
      run: npm run test:unit

    # - run: npm run test:integration
    # - run: npm run test:mainview
    # - run: npm run test:extension

    - name: Publish Mac
      run: npm run publish-mac

  linux:
    runs-on: ubuntu-latest

    env:
      USE_HARD_LINKS: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
        sudo /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install
      run: npm install

    - name: Build
      run: npm run build

    - name: Prepare
      run: npm run test:prepare:ci

    - name: Unit Test
      run: DISPLAY=:99.0 npm run test:unit

    # - run: npm run test:integration
    # - run: npm run test:mainview
    # - run: npm run test:extension

    - name: Publish Linux
      run: npm run publish-linux
